#FROM mcr.microsoft.com/dotnet/aspnet:5.0
#COPY bin/Release/netcoreapp3.1/publish/ App/
#WORKDIR /App
#ENTRYPOINT ["dotnet", "aspnetapp.dll"]

FROM ubuntu

# if we want to install via apt
USER root
RUN apt-get update
RUN apt-get install -y sudo

RUN sudo apt-get install -y wget

RUN wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN sudo dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb

# Install dotnet runtime
RUN sudo apt-get update && \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update
RUN sudo apt-get install -y aspnetcore-runtime-5.0
#RUN sudo apt-get install -y dotnet-runtime-5.0

# Load the Web API code
RUN echo .
COPY ./out /App
WORKDIR /App

# drop back to the regular jenkins user - good practice
#USER jenkins

ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000
ENTRYPOINT ["dotnet", "jokeapi.dll"]
